export const diagnoses = [
  "Infarto Agudo do Miocárdio",
  "Pneumonia",
  "Enxaqueca",
  "Gastrite",
  "Transtorno de Ansiedade",
  "Insuficiência Cardíaca",
];

export const mockPatients = [
  {
    id: 1,
    name: "Maria Santos",
    age: 65,
    gender: "Feminino",
    lastDiagnosis: "Insuficiência Cardíaca",
    riskLevel: "Alto",
    lastVisit: "2024-03-15",
    phone: "(11) 98765-4321",
    email: "maria.santos@email.com",
  },
  {
    id: 2,
    name: "João Oliveira",
    age: 58,
    gender: "Masculino",
    lastDiagnosis: "Infarto Agudo do Miocárdio",
    riskLevel: "Crítico",
    lastVisit: "2024-03-14",
    phone: "(11) 97654-3210",
    email: "joao.oliveira@email.com",
  },
  {
    id: 3,
    name: "Ana Pereira",
    age: 42,
    gender: "Feminino",
    lastDiagnosis: "Transtorno de Ansiedade",
    riskLevel: "Moderado",
    lastVisit: "2024-03-10",
    phone: "(11) 96543-2109",
    email: "ana.pereira@email.com",
  },
  {
    id: 4,
    name: "Pedro Costa",
    age: 35,
    gender: "Masculino",
    lastDiagnosis: "Enxaqueca",
    riskLevel: "Baixo",
    lastVisit: "2024-03-12",
    phone: "(11) 95432-1098",
    email: "pedro.costa@email.com",
  },
  {
    id: 5,
    name: "Lucia Ferreira",
    age: 52,
    gender: "Feminino",
    lastDiagnosis: "Pneumonia",
    riskLevel: "Moderado",
    lastVisit: "2024-03-13",
    phone: "(11) 94321-0987",
    email: "lucia.ferreira@email.com",
  },
];

export const mockAppointments = [
  {
    id: 1,
    patientId: 1,
    patientName: "Maria Santos",
    date: new Date().toISOString().split("T")[0],
    time: "09:00",
    diagnosis: "Insuficiência Cardíaca",
    status: "Confirmada",
    notes: "Avaliação de rotina",
  },
  {
    id: 2,
    patientId: 2,
    patientName: "João Oliveira",
    date: new Date().toISOString().split("T")[0],
    time: "10:30",
    diagnosis: "Infarto Agudo do Miocárdio",
    status: "Confirmada",
    notes: "Retorno pós-cirúrgico",
  },
  {
    id: 3,
    patientId: 3,
    patientName: "Ana Pereira",
    date: new Date().toISOString().split("T")[0],
    time: "14:00",
    diagnosis: "Transtorno de Ansiedade",
    status: "Pendente",
    notes: "Primeira consulta",
  },
];
